import Foundation

/// Microphone correction curve (UMIK-style text format: optional header
/// lines, then `frequency dB [phase]` pairs).
///
/// Two sources, one mechanism:
/// - Built-in per-device curves shipped with the app (generated by the
///   substitution method: a reference omni measurement mic and the phone
///   record the same stimulus at the same position; the curve is the
///   smoothed difference of their magnitude responses).
/// - User-loaded calibration files for external mics (miniDSP UMIK-1/2 etc.).
///
/// HARD RULE: calibration applies to frequency-response metrics ONLY.
/// Decay times (RT60/EDT/C50/C80) are relative, time-domain metrics; a
/// magnitude correction must never touch them. This is enforced
/// structurally — the decay pipeline has no calibration parameter.
public struct MicrophoneCalibration: Sendable {

    public struct Point: Sendable {
        public let frequency: Double
        public let gainDB: Double

        public init(frequency: Double, gainDB: Double) {
            self.frequency = frequency
            self.gainDB = gainDB
        }
    }

    /// Sorted by frequency, ascending.
    public let points: [Point]
    /// Human-readable origin ("UMIK-1 #7001234", "iPhone 12 built-in v0", …).
    public let label: String

    public init?(points: [Point], label: String) {
        guard points.count >= 2 else { return nil }
        self.points = points.sorted { $0.frequency < $1.frequency }
        self.label = label
    }

    /// Parse a calibration text file. Header lines (e.g. UMIK's
    /// `"Sens Factor =…"`) and malformed lines are skipped; data lines are
    /// `frequency gain [phase]`, whitespace/tab separated, dot or comma
    /// decimals. Returns nil when fewer than two valid points are found.
    public init?(text: String, label: String) {
        func number(_ token: any StringProtocol) -> Double? {
            if let v = Double(token) { return v }
            if token.contains(","), !token.contains(".") {
                return Double(token.replacingOccurrences(of: ",", with: "."))
            }
            return nil
        }
        var parsed: [Point] = []
        for line in text.split(whereSeparator: \.isNewline) {
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            guard !trimmed.isEmpty, !trimmed.hasPrefix("*"), !trimmed.hasPrefix("#"),
                  !trimmed.hasPrefix("\"")
            else { continue }
            let tokens = trimmed.split(whereSeparator: { $0 == " " || $0 == "\t" })
            guard tokens.count >= 2,
                  let freq = number(tokens[0]), freq > 0,
                  let gain = number(tokens[1])
            else { continue }
            parsed.append(Point(frequency: freq, gainDB: gain))
        }
        self.init(points: parsed, label: label)
    }

    /// Mic gain at a frequency: log-frequency linear interpolation, clamped
    /// to the curve's end values outside its range.
    public func gain(at frequency: Double) -> Double {
        guard let first = points.first, let last = points.last else { return 0 }
        if frequency <= first.frequency { return first.gainDB }
        if frequency >= last.frequency { return last.gainDB }
        var low = points[0]
        for high in points.dropFirst() {
            if frequency <= high.frequency {
                let span = log(high.frequency / low.frequency)
                guard span > 0 else { return high.gainDB }
                let t = log(frequency / low.frequency) / span
                return low.gainDB + t * (high.gainDB - low.gainDB)
            }
            low = high
        }
        return last.gainDB
    }

    /// Correct a measured magnitude curve: the mic's own response is
    /// subtracted, leaving the room + system response.
    public func applied(to curve: FrequencyResponse.Curve) -> FrequencyResponse.Curve {
        let corrected = zip(curve.frequencies, curve.levelsDB).map { f, level in
            level - gain(at: f)
        }
        return FrequencyResponse.Curve(frequencies: curve.frequencies, levelsDB: corrected)
    }
}
